version: '3.1'
services:
  db:
    image: mysql:${DB_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE:      ${DB_NAME}
      MYSQL_USER:          ${DB_USER}
      MYSQL_PASSWORD:      ${DB_PASS}
  adminer:
    image: adminer
    ports:
    - '8080:8080'
    restart: always
    links:
      - db